### ISSUE TITLE
Externalize Constants

### ISSUE THREAD

**Issue by joshuafeldman** [pierrotsmnrd/grabKit#1]
This library looks very promising. It would be great if we could externalize the constants for the various service's information, like application ids, keys, etc. This way no modifications to the actual source need to be made to get the application running.

Maybe create a configuration class which we can subclass which returns the various values, and then we instantiate the base with that instance.

Just a thought.

**Comment by pierrotsmnrd** [comment]
Thanks for reporting :) 
I already thought about doing something similar to what is done in ShareKit, with the class DefaultSHKConfigurator. The main advantage is that you only need one file to configure, not one file per service, and as you wrote : there would be no need to modify the source.

I add this to my todo list ;)

**Comment by pierrotsmnrd** [comment]
This issue is fixed in GrabKit v1.1, committed one hour ago :)
Refer to the protocol GRKConfiguratorProtocol and the class myGrabKitConfigurator in the demo project.

Thanks for helping ! :)
