### ISSUE TITLE
Version tag

### ISSUE THREAD

**Issue by zrxq** [pierrotsmnrd/grabKit#11]
Could you please create a version tag in the repo? Like, `v1.2` or `1.2.0` or whatever. That would help me to create a clean [cocoapod](http://github.com/CocoaPods/CocoaPods) for the library.

Thanks!

**Comment by pierrotsmnrd** [comment]
I tagged the 3 versions : v1.0, v1.1 and v1.2. 
I'll keep on tagging at each new version.
Thanks for helping improving GrabKit :)

**Comment by zrxq** [comment]
Thanks! http://cocoapods.org/?q=grabKit/

**Comment by pierrotsmnrd** [comment]
Can you edit the description please ? to fit to the grabkit's description on github : "Simple access on iOS to your photos on Facebook, FlickR, Instagram, Picasa, and more "

**Comment by zrxq** [comment]
Done.  

## 

Zoreslav Khimich
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)
