### ISSUE TITLE
There's no handler for applicationDidBecomeActive during OAuth

### ISSUE THREAD

**Issue by zrxq** [pierrotsmnrd/grabKit#12]
If an authentication session gets cancelled (e.g., the user closes Safari) there is no way to tell the active connector to reset it's own or underlying client library's state.

For example, Facebook iOS SDK has `[FBSession handleDidBecomeActive]`. I believe it would be a good idea to provide a method in, say, `GRKConnectorsDispatcher` for that.

**Comment by pierrotsmnrd** [comment]
Fixed in commit 61a9ca253c887268de436c569a1d3556673e7622 :)

**Comment by zrxq** [comment]
Thank you!
