### ISSUE TITLE
FacebookSDK mismatch

### ISSUE THREAD

**Issue by drhr** [pierrotsmnrd/grabKit#13]
Looks like your FacebookSDK.framework is out of date?

There was a recent pull request that updated GRKFacebookConnector.m to use FBSession::openActiveSessionWithReadPermissions instead of the outdated FBSession::openActiveSessionWithPermissions.

However, the FacebookSDK.framework you have in the repository is using that outdated FBSession::openActiveSessionWithPermissions.

**Comment by pierrotsmnrd** [comment]
Absolutely :) I'm working on it, thanks for reporting. Next version of GrabKit will not embed Facebook's framework anymore, I'll update the documentation to help add it to the final user's project, so the next version will take a bit of time ... :)

**Comment by pierrotsmnrd** [comment]
No don't close it now :) We'll close it when it's done :p

**Comment by drhr** [comment]
Oops I must have accidentally hit Close & Comment..

**Comment by pierrotsmnrd** [comment]
That happens ;)

**Comment by pierrotsmnrd** [comment]
It's now fixed in GrabKit V1.2.2, commit e5f18c7f2217f5440cb9b2736296ee8be4975674 :)
