### ISSUE TITLE
No albums (in sim) causes uncaught exception

### ISSUE THREAD

**Issue by ndcoxhead** [pierrotsmnrd/grabKit#14]
I get this in the simulator, not sure if it can happen on a device if there are no albums present.
In fillCoverPhotoOfAlbum:andCompleteBlock:andErrorBlock it crashes doing this line:
   [groupForThisAlbum  enumerateAssetsAtIndexes:indexSetOfAssetToRetrieve
                                         options:0 
                                      usingBlock:^(ALAsset *result, NSUInteger index, BOOL *stop)

album.count is 0, and I've changed the code to make sure in this case it uses:
indexSetOfAssetToRetrieve = [NSIndexSet indexSetWithIndex:0];
instead of indexSetOfAssetToRetrieve = [NSIndexSet indexSetWithIndex:album.count-1];
but anyway it still does:
**\* Terminating app due to uncaught exception 'NSRangeException', reason: 'indexSet count or lastIndex must not exceed -numberOfAssets'

**Comment by pierrotsmnrd** [comment]
It should be fixed with the commit f02e9c370b20224b3e3d87bc2ba1275a4c574504 :) thanks a lot for reporting !
