### ISSUE TITLE
Photo.Comments & Search

### ISSUE THREAD

**Issue by myeyesareblind** [pierrotsmnrd/grabKit#15]
I am working on application which must have the search option (search by tag, global search, not the user photos) and which also should do the retrieving comments for the photos.
Any plans on adding those features to the grabKit?

Great library, thank you for doing this.

**Comment by pierrotsmnrd** [comment]
I wanted to add these features when I began creating GrabKit, but it's not done yet because it takes a lot of time :) so, "in the future" it'll be done, but I can't tell you when.

Thanks for your kind words :)
