### ISSUE TITLE
grabKit + cocoapods

### ISSUE THREAD

**Issue by myeyesareblind** [pierrotsmnrd/grabKit#16]
Looks like Picasa classes are missing from cocoapods (grabKit (1.2.1)).

**Comment by pierrotsmnrd** [comment]
They are missing from cocoapods, I guess there is no cocoapod created for Google Data's project (it's split in several SVNs here and there, a bit messy by the way)

In GrabKit V1.2.2, I've added a bash script to download the needed file from Google's SVNs. not as handy as cocoapods for some of you, but that's still a solution anyway.
