### ISSUE TITLE
Can't build demo app

### ISSUE THREAD

**Issue by madeonamac** [pierrotsmnrd/grabKit#18]
I have tried to build the demo app following the instructions but can not seem to get it to work. I cloned the repo, I am on the latest Xcode/iOS. Is it still working or is it just me?

**Comment by pierrotsmnrd** [comment]
What are your errors ?

**Comment by pierrotsmnrd** [comment]
Have you properly followed this tutorial ?

https://github.com/pierrotsmnrd/grabKit/wiki/How-to-run-GrabKit's-demo-application

**Comment by pierrotsmnrd** [comment]
Still no answer ... 3 days left before I close this ticket.

**Comment by madeonamac** [comment]
Sorry - been away. Yes I followed the instructions and had no joy. Weirdly I have succeeded in the past - not sure if it is a new xcode issue or what. I will try again and send you the errors.

**Comment by pierrotsmnrd** [comment]
2 weeks later, still no answer : issue closed.
