### ISSUE TITLE
Authentication in a modal dialog webview

### ISSUE THREAD

**Issue by fvisticot** [pierrotsmnrd/grabKit#19]
Can you please explain or improve the current framework to allow authentication in a modal dialog view ? (I'm not a big fan of launching a separate browser...).

Tx

**Comment by pierrotsmnrd** [comment]
No.
_ Some SDK don't make this possible.
_ By opening Safari, the user benefits of SSO (single sign-on).
_ Skeptical / Paranoid users are reassured : they can check the opened URL, and verify they are not redirected in a scam page or whatever could scare them.
