### ISSUE TITLE
facebook grab photos number problem 

### ISSUE THREAD

**Issue by MYX2012** [pierrotsmnrd/grabKit#21]
hi,guy,i have a problem when use grabkit demo.
when  i post more than one photo to the facebook one time, the album list display the righ photo number ,but grab the photos list is less ,Why?

**Comment by pierrotsmnrd** [comment]
If there are less photos in the list than expected, it may mean that Facebook didn't return some of them, for various reasons, like cache needing to be invalidated for example.
Did you retry after a while, to see if the photos list has still missing photos ?

**Comment by MYX2012** [comment]
the problem is exist if i use iphone facebook app to post a message with some photos.
you can try by just post a message with more than one photo , and see the demo if it can display the right number of photos.

**Comment by pierrotsmnrd** [comment]
Can't reproduce.
