### ISSUE TITLE
If facebook photos are not in a album, how to get them?

### ISSUE THREAD

**Issue by wenwuwang** [pierrotsmnrd/grabKit#23]
If facebook photos are not in a album, grabKit can not get them, would you consider to add similar interface?

**Comment by pierrotsmnrd** [comment]
On Facebook, how can a photo not be in an album ?

**Comment by wenwuwang** [comment]
It's my fault, if i upload photos, but not create a album, these photos will be saved to a unnamed album.

**Comment by pierrotsmnrd** [comment]
ok ;)
