### ISSUE TITLE
Picasa grabber: Could be faster ?

### ISSUE THREAD

**Issue by fvisticot** [pierrotsmnrd/grabKit#24]
I have made some tests and my feeling is that getting photos from Picasa can take some time... 16s on my iPad3 for 1000 photos
1. Is it due to the huge quantitie of info returned by the server
2. Is it due to XML parsing ? (I think picasa API is using XML not JSON)
3. Is it possible to use json and improve speed ?

**Comment by pierrotsmnrd** [comment]
Hi.

Yes, Picasa is slow. but as you noticed, Picasa API is not using JSON, only XML feeds.

But how do you load 1000 photos ? Are you using the picker, or are you using grabkit as a lib and calling the grabbers manually ? 
If you use the picker : does it take 16 seconds to show all thumbnails from the first to the last, or ... ?

Thanks.

**Comment by pierrotsmnrd** [comment]
No answer since 2 months : ticket closed
