### ISSUE TITLE
cocoapods version is still 1.2.1

### ISSUE THREAD

**Issue by dreampowder** [pierrotsmnrd/grabKit#25]
hi there, i've tried to install this component from cocoapods and it install 1.2.1, can you please update the podspec file?

**Comment by pierrotsmnrd** [comment]
Hi :) 

For, sorry for the late answer :)

I've written two podspecs, one for GrabKit v1.3 and another for GrabKit v1.3.1, and I've made a pull request to add them to Cocoapods/specs.

I'll keep you informed once the pull request has been merged :)

**Comment by pierrotsmnrd** [comment]
The pull request has been merged. GrabKit v1.3 and v1.3.1 are now available from Cocoapods.
https://github.com/CocoaPods/Specs/pull/2198

**Comment by dreampowder** [comment]
Thanks for the fix and for this wonderful library.
