### ISSUE TITLE
Turkish Localization

### ISSUE THREAD

**Issue by dreampowder** [pierrotsmnrd/grabKit#26]
hi there, just added turkish localization file to the grabkitpicker. how can i upload the modified file? heres the string contents: 

"GRK_ALBUMS_LIST_NEED_TO_CONNECT" = "%serviceName% servisine giriş yapmanız gerekmektedir.";

"GRK_ALBUMS_LIST_CONNECT_BUTTON" = "Giriş";

"GRK_ALBUMS_LIST_ERROR_RETRY" = "Bir hata oluştu, lütfen tekrar deneyin.";

"GRK_ALBUMS_LIST_HUD_LOADING" = "Yükleniyor ...";

"GRK_ALBUMS_LIST_ALL_ALBUMS_LOADED" = "Bütün albümler yüklendi.";

"GRK_USER_VIEW_LOGOUT" = "Çıkış";

"GRK_LOAD_MORE_CELL_ERROR_RETRY" = "Bir hata oluştu, lütfen tekrar deneyin.";

"GRK_LOAD_MORE_CELL_LOAD_MORE" = "Daha...";

"GRK_SERVICES_LIST_TITLE" = "Sosyal Ağlar";

"GRK_FACEBOOK_TAGGED_PHOTOS" = "İşaretlenmiş Fotoğraflar";

**Comment by pierrotsmnrd** [comment]
Merhaba, ve teşekkürler ;)

Thanks a lot for your help. I'll add your translation into the next version of GrabKit :)

**Comment by dreampowder** [comment]
i thank you, i'd love to help more when i can.

**Comment by pierrotsmnrd** [comment]
Commit 8dffb84309ffcf6fafea2de13f31fe4649488450
