### ISSUE TITLE
iphone/device Picker issue: Some photos are not selectable

### ISSUE THREAD

**Issue by clientmedia** [pierrotsmnrd/grabKit#27]
I am testing with iPhone 4 + ios6 and on albums with more than 1 page, picker will not select some photos. ie. Tap on some photos does not show the selection check. 

Seems to be working fine for remote sources.

Thanks

**Comment by pierrotsmnrd** [comment]
Are the photos already loaded when you try to select them ?

**Comment by clientmedia** [comment]
Yes, the photos are loaded and thumbs displayed in the grid. Its happens
with bigger albums. I can select most but random thumbs are not selected as
if tap was not recognized.
Tested with ios 6 on iphone 4

**Comment by pierrotsmnrd** [comment]
Ok, I'm investigating. 
If you find any way to reproduce this bug on demand, let me know.

**Comment by clientmedia** [comment]
Did some basic testing to reproduce.

On any Album with > 30 photos, I can't select photo 29,30,31,32. Photo 33
is selectable. After that random photos are selectable.  Tested for phone
and facebook as source.

Weird that I can't see the same behavior on the 5.1 or 6.0 simulator. Only
on the device. Running on iphone 4 with OS 6.1

Thanks

**Comment by pierrotsmnrd** [comment]
I found the origin of the bug : in GRKPickerPhotosListThumbnail.m, in the method prepareForReuse, I forgot to add " self.selected = NO; "
So, when reusing a thumbnail, if it was previously selected, the new thumbnail was considered as already selected. 

4d5328ff8c380965d4eb25e9c7d2d7d1ae38ad1b
