### ISSUE TITLE
Translation help.

### ISSUE THREAD

**Issue by tianye2856** [pierrotsmnrd/grabKit#28]
Hi pierrotsmnrd, I could help you translate grabKit into Simplified Chinese.
If you need my help, just send the strings to tianye2856@outlook.com

**Comment by pierrotsmnrd** [comment]
Hi :) 

To have a translation of GrabKit in Simplified Chinese, all you have to do is to translate this strings file : 

https://github.com/pierrotsmnrd/grabKit/blob/master/grabKit/grabKit/GrabKitPicker/Resources/en.lproj/GrabKitPicker.strings

Then you can either make a pull request, or put the content of this file here in the comments.

Thanks  :)

**Comment by pierrotsmnrd** [comment]
see issue #29
