### ISSUE TITLE
Trying to set redirect uri in instagram but I get an error

### ISSUE THREAD

**Issue by aaronksaunders** [pierrotsmnrd/grabKit#3]
You must enter an absolute URI that starts with http:// or https://

trying to set the redirect_uri to my application url

**Comment by pierrotsmnrd** [comment]
Can you be more explicit please ?

If the problem occurs when you are registering your application on Instagram : Please give me more details. because I've just tried and it worked fine ...

**Comment by aaronksaunders** [comment]
I set the information in instagram using callback uri `grabkitdemo://`

Set the information in the code `NSString * const kGRKInstagramRedirectUri = @"grabkitdemo://";`

[app.plist screencap](https://skitch.com/unnamed-bpf6e/ejbdp/grabkit.xcodeproj-grabkitdemo-info.plist)

but I still get an error trying to redirect back to app

**Comment by pierrotsmnrd** [comment]
Remove the "://" in your URL schemes in your plist file, and try again.

**Comment by aaronksaunders** [comment]
thanks

**Comment by pierrotsmnrd** [comment]
You're welcome :) Thanks for trying GrabKit :)
If you find any other bug, open another issue.
And don't hesitate to give me suggestions :)

**Comment by carobeta** [comment]
@aaronksaunders I have the same issue. It's possible redirect to the app? What url you add into instagram developer page if you must enter an absolute URI that starts with http:// or https://. 

I don't understand, can you share an example? 

Thanks!
