### ISSUE TITLE
adding additional source for taking photo from camera... 

### ISSUE THREAD

**Issue by steve21124** [pierrotsmnrd/grabKit#30]
to add additional photo source from camera, which class is best to overwrite? GRKPickerViewController?

**Comment by pierrotsmnrd** [comment]
I don't understand what you want to achieve. What do you call a "photo source _from camera_ " ?

**Comment by steve21124** [comment]
i mean to add camera as additional photo source. currently,it only has taking from photo library

**Comment by pierrotsmnrd** [comment]
What you want is just showing a UIImagePickerController to the user. no need for an "additional photo source".
