### ISSUE TITLE
xib resources not copied when using CocoaPods

### ISSUE THREAD

**Issue by bh213** [pierrotsmnrd/grabKit#31]
This is for grabKit version 1.3.1, if I add the following line to podspec , it seems to work:

  s.resources = 'grabKit/grabKit/*_/_.{xib}'

**Comment by pierrotsmnrd** [comment]
I've committed a fix, the pull request is waiting for approval.
https://github.com/CocoaPods/Specs/pull/3243

**Comment by pierrotsmnrd** [comment]
The pull request has been merged

**Comment by pierrotsmnrd** [comment]
https://github.com/CocoaPods/Specs/commit/248aa578a301ea3d67eca6acdab2a192e02b3fcd
