### ISSUE TITLE
The git submodules file has inconsistent capitalization of it's directories. This causes submodule init to fail.

### ISSUE THREAD

**Issue by jquave** [pierrotsmnrd/grabKit#34]
https://github.com/pierrotsmnrd/grabKit/blob/master/.gitmodules

**Comment by pierrotsmnrd** [comment]
Where does it fail ?

**Comment by pierrotsmnrd** [comment]
ok got it

**Comment by pierrotsmnrd** [comment]
everything is lowercase now : https://github.com/pierrotsmnrd/grabKit/commit/46d6b55271670b6a2ae9f33de5e1e5a764cf0729
