### ISSUE TITLE
AssetsLibrary.framework needs to be added when installed from cocoapods

### ISSUE THREAD

**Issue by dreampowder** [pierrotsmnrd/grabKit#37]
Hi there, i get those errors on my project when i add grabkit from cocoapods. i got the following error, which i solved by adding AssetsLibrary.framework to the project.

Undefined symbols for architecture i386:
  "_ALAssetPropertyDate", referenced from:
      -[GRKDeviceGrabber photoFromALAsset:atIndex:] in libPods.a(GRKDeviceGrabber.o)
  "_ALAssetPropertyRepresentations", referenced from:
      -[GRKDeviceGrabber photoFromALAsset:atIndex:] in libPods.a(GRKDeviceGrabber.o)
  "_ALAssetsGroupPropertyName", referenced from:
      ___108-[GRKDeviceGrabber albumsOfCurrentUserAtPageIndex:withNumberOfAlbumsPerPage:andCompleteBlock:andErrorBlock:]_block_invoke in libPods.a(GRKDeviceGrabber.o)
  "_ALAssetsGroupPropertyPersistentID", referenced from:
      ___108-[GRKDeviceGrabber albumsOfCurrentUserAtPageIndex:withNumberOfAlbumsPerPage:andCompleteBlock:andErrorBlock:]_block_invoke in libPods.a(GRKDeviceGrabber.o)
  "_ALAssetsGroupPropertyType", referenced from:
      -[GRKDeviceGrabber fillCoverPhotoOfAlbum:andCompleteBlock:andErrorBlock:] in libPods.a(GRKDeviceGrabber.o)
  "_OBJC_CLASS_$_ALAssetsFilter", referenced from:
      objc-class-ref in libPods.a(GRKDeviceGrabber.o)
  "_OBJC_CLASS_$_ALAssetsLibrary", referenced from:
      objc-class-ref in libPods.a(GrabKitDemoHomeViewController.o)
      objc-class-ref in libPods.a(GRKPickerThumbnailManager.o)
      objc-class-ref in libPods.a(GRKDeviceGrabber.o)
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by pierrotsmnrd** [comment]
This fix in the podspec should fix the problem : 
 https://github.com/CocoaPods/Specs/commit/248aa578a301ea3d67eca6acdab2a192e02b3fcd
