### ISSUE TITLE
Allows Editing

### ISSUE THREAD

**Issue by joshuafeldman** [pierrotsmnrd/grabKit#4]
It would be really cool to have an allows editing property like Apple's from their photo picker. Allowing the user to crop the photo selected from a service into a square. It could be easily written. I am pretty swamped right now, but if I can find some time I will tackle it.

**Comment by pierrotsmnrd** [comment]
I'm not sure to really understand. Can you please give me more details ?

**Comment by joshuafeldman** [comment]
Apple's UIImagePickerController has a property allowsEditing. When set to YES it provides a view after you've selected a photo that allows the user to crop and scale the photo. Than once they are done it returns that cropped photo.

It would be cool to have that option in GrabKit.

**Comment by pierrotsmnrd** [comment]
This should not be a feature in GrabKit, but in a controller using GrabKit.
