### ISSUE TITLE
What would it take to add GEO-tag info to GRKPhoto?

### ISSUE THREAD

**Issue by jasperblues** [pierrotsmnrd/grabKit#40]
What would it take to add GEO-tag info to GRKPhoto?

Do the individual SDKs bring this information back in the results? Or do we have to search by location first?

In the former case, we could contribute this feature.

**Comment by pierrotsmnrd** [comment]
Retrieving the GEO-tags on GRKPhoto is planned for a future release. Stay tuned :)
