### ISSUE TITLE
libxml/tree.h not found

### ISSUE THREAD

**Issue by dreampowder** [pierrotsmnrd/grabKit#42]
i got this annoying problem when i create a new project and add grabkit from cocoapods.. 

it says there is a problem with gData, tried everything but no luck...

**Comment by pierrotsmnrd** [comment]
did you try this ? 
http://stackoverflow.com/questions/1428847/libxml-tree-h-no-such-file-or-directory

**Comment by dreampowder** [comment]
i think i found the problem. Somehow i have 2 versions of cocoapods on my system. one is extremely old, and other one is up-to-date. when i update pod it updates the new one but when i type "which pod" it says i am using the old one. it tool days to solve this problem but now its fixed. 

So this problem is solved by using the latest version of cocoapods. Thanks!
