### ISSUE TITLE
"GTMOAuth2ViewTouch.xib"

### ISSUE THREAD

**Issue by pindoria** [pierrotsmnrd/grabKit#43]
"Interface Builder could not open the document "GTMOAuth2ViewTouch.xib" because it does not exist."

**Comment by pierrotsmnrd** [comment]
It seems that you didn't complete the process to set up GrabKit's dependencies. Gdata is missing.
_ If you use podspecs, please check that Gdata is in grabKit/submodules/Picasa. 
_ If you don't, run the script grabKit/submodules/installSubmodules.sh

**Comment by DaveThePianoDude** [comment]
Ran into this problem as well.  I should be able to clone the project to my desktop and run it.
