### ISSUE TITLE
Device grabber reverse order

### ISSUE THREAD

**Issue by albertoramonj** [pierrotsmnrd/grabKit#56]
I'm trying to show all the photos from an album in reverse order (from newest to oldest). I've tried with the ALAssetsGroup option "NSEnumerationReverse" but it only seems to work with one-page albums.

Thanks a lot for your work!.

**Comment by albertoramonj** [comment]
Ok, I see now. It only reverses each enumeration of k photos (1 page). Any way to invert the order the savedPhotos pages are loaded?. Thanks!

**Comment by albertoramonj** [comment]
Nevermind, I finally got it. Playing with NSMakeRange, NSIndexSet and the enumerateAssetsAtIndexes NSEnumerationReverse option on the GRKDeviceGrabber.m did the trick.

Thank you very much again.

**Comment by padamthapa** [comment]
Can you tell what exactly you changed to get this result ? I also need photos in reverse (recent to past)! Thanks.

**Comment by albertoramonj** [comment]
Open GRKDeviceGrabber.m and go to fillAlbum:(GRKAlbum *)album method. First, replace lines 334 to 344 with:

```
        NSRange range = NSMakeRange(0, finalNumberOfPhotosPerPage);
        indexSetAtThisPageIndex = [NSIndexSet indexSetWithIndexesInRange:range];
```

Then, the original 347 line with:

```
        NSRange range = NSMakeRange(album.count-(numberOfPhotosPerPage*(pageIndex+1)), numberOfPhotosPerPage);
        indexSetAtThisPageIndex = [NSIndexSet indexSetWithIndexesInRange:range];
```

Finally, the original 362 line with:

```
        op:NSEnumerationReverse;
```

I think that's it. Hope it helps.

**Comment by padamthapa** [comment]
Thanks a lot. Its worked.
