### ISSUE TITLE
Code inside of connectWithConnectionIsCompleteBlock is Not Executed!!!

### ISSUE THREAD

**Issue by virindh** [pierrotsmnrd/grabKit#9]
This is a great library( I'm using for Picasa) until it stopped working. All of a sudden the code inside of connectWithConnectionIsCompleteBlock dosent work. No login window. No Nothing. :(  please help.....

**Comment by pierrotsmnrd** [comment]
Nothing changed "all of a sudden" in grabKit's code.
Can you give me more details please ?

**Comment by virindh** [comment]
I found the issue after looking at the example project... It turns out that you need to check the isConnected method and go from there rather than use connectwithconnection every time.

**Comment by pierrotsmnrd** [comment]
That's right. But your comment is interesting. Maybe some methods are not explicit or intuitive enough (even though I tried to do my best to make the code explicit and intuitive :p ).
